"""
Credit spread strategy engine for SPX 0DTE.

Implements three strategy variants:
1. Bull Put Spread  - Sell OTM put spread (bullish bias)
2. Bear Call Spread - Sell OTM call spread (bearish bias)
3. Iron Condor      - Sell both sides (neutral bias)

Entry signals are based on:
- Delta targeting (sell strikes at specific delta levels)
- VIX filtering (adequate premium environment)
- Time-of-day windows
- Intraday momentum and mean reversion signals
"""

import logging
from dataclasses import dataclass
from datetime import datetime, time
from typing import Optional
from zoneinfo import ZoneInfo

from spx_bot.config import AppConfig, StrategyType, config
from spx_bot.market_data import OptionsChain, OptionType, SpxSnapshot
from spx_bot.orders import Order, OrderType, SpreadLeg, SpreadSide

logger = logging.getLogger(__name__)

ET = ZoneInfo("America/New_York")


@dataclass
class TradeSignal:
    """A trade signal generated by the strategy engine."""
    strategy: StrategyType
    spread_side: SpreadSide
    short_strike: float
    long_strike: float
    credit: float
    max_loss_per_contract: float
    contracts: int
    confidence: float  # 0-1 score
    reason: str

    @property
    def total_credit(self) -> float:
        return self.credit * 100 * self.contracts

    @property
    def total_max_loss(self) -> float:
        return self.max_loss_per_contract * self.contracts

    def to_order(self) -> Order:
        """Convert signal to a submittable order."""
        if self.spread_side == SpreadSide.BULL_PUT:
            legs = [
                SpreadLeg(
                    symbol=f"SPX_P{self.short_strike:.0f}",
                    strike=self.short_strike,
                    action="SELL",
                    quantity=self.contracts,
                    option_type="put",
                ),
                SpreadLeg(
                    symbol=f"SPX_P{self.long_strike:.0f}",
                    strike=self.long_strike,
                    action="BUY",
                    quantity=self.contracts,
                    option_type="put",
                ),
            ]
        else:
            legs = [
                SpreadLeg(
                    symbol=f"SPX_C{self.short_strike:.0f}",
                    strike=self.short_strike,
                    action="SELL",
                    quantity=self.contracts,
                    option_type="call",
                ),
                SpreadLeg(
                    symbol=f"SPX_C{self.long_strike:.0f}",
                    strike=self.long_strike,
                    action="BUY",
                    quantity=self.contracts,
                    option_type="call",
                ),
            ]

        return Order(
            spread_side=self.spread_side,
            legs=legs,
            quantity=self.contracts,
            order_type=OrderType.CREDIT,
            limit_price=self.credit,
        )


class CreditSpreadStrategy:
    """
    Core strategy engine for 0DTE credit spreads.

    Scans the options chain for high-probability setups based on
    delta targeting, VIX environment, and time-of-day filters.
    """

    def __init__(self, cfg: AppConfig = config, backtest_mode: bool = False):
        self.cfg = cfg
        self.backtest_mode = backtest_mode

    def scan_for_signals(
        self,
        chain: OptionsChain,
        snapshot: SpxSnapshot,
        max_position_size: float,
        contracts_calculator: callable,
    ) -> list[TradeSignal]:
        """
        Scan the current options chain for valid trade setups.

        Returns a list of TradeSignal objects sorted by confidence.
        """
        signals = []
        now = datetime.now(ET)

        # Time-of-day filter (bypassed in backtest mode)
        if not self.backtest_mode and not self._in_trading_window(now):
            logger.debug("Outside trading window, skipping scan")
            return signals

        # VIX filter
        if not self._vix_acceptable(snapshot.vix):
            logger.info("VIX %.2f outside range [%.1f, %.1f]",
                        snapshot.vix, self.cfg.strategy.min_vix, self.cfg.strategy.max_vix)
            return signals

        # Determine market bias from intraday price action
        bias = self._assess_bias(snapshot)

        # Scan each enabled strategy
        for strategy_type in self.cfg.strategy.enabled_strategies:
            if strategy_type == StrategyType.BULL_PUT_SPREAD and bias in ("bullish", "neutral"):
                signal = self._scan_bull_put(chain, snapshot, max_position_size, contracts_calculator, bias)
                if signal:
                    signals.append(signal)

            elif strategy_type == StrategyType.BEAR_CALL_SPREAD and bias in ("bearish", "neutral"):
                signal = self._scan_bear_call(chain, snapshot, max_position_size, contracts_calculator, bias)
                if signal:
                    signals.append(signal)

            elif strategy_type == StrategyType.IRON_CONDOR and bias == "neutral":
                put_signal = self._scan_bull_put(chain, snapshot, max_position_size / 2, contracts_calculator, bias)
                call_signal = self._scan_bear_call(chain, snapshot, max_position_size / 2, contracts_calculator, bias)
                if put_signal and call_signal:
                    signals.extend([put_signal, call_signal])

        signals.sort(key=lambda s: s.confidence, reverse=True)
        return signals

    def _scan_bull_put(
        self,
        chain: OptionsChain,
        snapshot: SpxSnapshot,
        max_size: float,
        contracts_calc: callable,
        bias: str,
    ) -> Optional[TradeSignal]:
        """Look for a bull put spread setup."""
        short_put = chain.find_by_delta(
            OptionType.PUT,
            self.cfg.strategy.short_put_delta,
        )
        if not short_put:
            return None

        # Long put is spread_width points below
        long_strike = short_put.strike - self.cfg.strategy.spread_width
        long_put = chain.find_by_strike(OptionType.PUT, long_strike)
        if not long_put:
            return None

        credit = round(short_put.mid - long_put.mid, 2)
        spread_width = self.cfg.strategy.spread_width

        # Credit must meet minimum threshold
        min_credit = spread_width * self.cfg.strategy.min_credit_pct
        if credit < min_credit:
            logger.debug(
                "Bull put credit $%.2f below minimum $%.2f", credit, min_credit
            )
            return None

        max_loss_per_contract = (spread_width - credit) * 100
        contracts = contracts_calc(max_loss_per_contract)
        if contracts <= 0:
            return None

        # Confidence scoring
        confidence = self._score_setup(
            credit=credit,
            spread_width=spread_width,
            delta=abs(short_put.greeks.delta) if short_put.greeks else 0.16,
            vix=snapshot.vix,
            bias=bias,
            side="put",
        )

        return TradeSignal(
            strategy=StrategyType.BULL_PUT_SPREAD,
            spread_side=SpreadSide.BULL_PUT,
            short_strike=short_put.strike,
            long_strike=long_strike,
            credit=credit,
            max_loss_per_contract=max_loss_per_contract,
            contracts=contracts,
            confidence=confidence,
            reason=(
                f"Bull put {short_put.strike}/{long_strike} "
                f"credit=${credit:.2f} delta={short_put.greeks.delta:.3f} "
                f"bias={bias}"
            ),
        )

    def _scan_bear_call(
        self,
        chain: OptionsChain,
        snapshot: SpxSnapshot,
        max_size: float,
        contracts_calc: callable,
        bias: str,
    ) -> Optional[TradeSignal]:
        """Look for a bear call spread setup."""
        short_call = chain.find_by_delta(
            OptionType.CALL,
            self.cfg.strategy.short_call_delta,
        )
        if not short_call:
            return None

        long_strike = short_call.strike + self.cfg.strategy.spread_width
        long_call = chain.find_by_strike(OptionType.CALL, long_strike)
        if not long_call:
            return None

        credit = round(short_call.mid - long_call.mid, 2)
        spread_width = self.cfg.strategy.spread_width

        min_credit = spread_width * self.cfg.strategy.min_credit_pct
        if credit < min_credit:
            logger.debug(
                "Bear call credit $%.2f below minimum $%.2f", credit, min_credit
            )
            return None

        max_loss_per_contract = (spread_width - credit) * 100
        contracts = contracts_calc(max_loss_per_contract)
        if contracts <= 0:
            return None

        confidence = self._score_setup(
            credit=credit,
            spread_width=spread_width,
            delta=abs(short_call.greeks.delta) if short_call.greeks else 0.16,
            vix=snapshot.vix,
            bias=bias,
            side="call",
        )

        return TradeSignal(
            strategy=StrategyType.BEAR_CALL_SPREAD,
            spread_side=SpreadSide.BEAR_CALL,
            short_strike=short_call.strike,
            long_strike=long_strike,
            credit=credit,
            max_loss_per_contract=max_loss_per_contract,
            contracts=contracts,
            confidence=confidence,
            reason=(
                f"Bear call {short_call.strike}/{long_strike} "
                f"credit=${credit:.2f} delta={short_call.greeks.delta:.3f} "
                f"bias={bias}"
            ),
        )

    def _assess_bias(self, snapshot: SpxSnapshot) -> str:
        """
        Determine intraday market bias from price action.

        Uses change from open and intraday range position.
        """
        change_pct = snapshot.change_from_open_pct

        # Strong directional move
        if change_pct > 0.3:
            return "bullish"
        elif change_pct < -0.3:
            return "bearish"

        # Check where price sits in intraday range
        if snapshot.intraday_range > 0:
            range_position = (snapshot.price - snapshot.daily_low) / snapshot.intraday_range
            if range_position > 0.7:
                return "bullish"
            elif range_position < 0.3:
                return "bearish"

        return "neutral"

    def _score_setup(
        self,
        credit: float,
        spread_width: float,
        delta: float,
        vix: float,
        bias: str,
        side: str,
    ) -> float:
        """Score a trade setup from 0.0 to 1.0."""
        score = 0.5  # baseline

        # Credit richness (higher credit / spread width = better)
        credit_ratio = credit / spread_width
        if credit_ratio > 0.40:
            score += 0.15
        elif credit_ratio > 0.35:
            score += 0.10

        # Delta sweet spot (0.12-0.20 ideal)
        if 0.12 <= delta <= 0.20:
            score += 0.15
        elif 0.10 <= delta <= 0.25:
            score += 0.05

        # VIX environment (higher VIX = richer premium)
        if 16 <= vix <= 25:
            score += 0.10
        elif 25 < vix <= 35:
            score += 0.05

        # Bias alignment
        if side == "put" and bias == "bullish":
            score += 0.10
        elif side == "call" and bias == "bearish":
            score += 0.10
        elif bias == "neutral":
            score += 0.05

        return min(1.0, max(0.0, round(score, 2)))

    def _in_trading_window(self, now: datetime) -> bool:
        """Check if current time is within allowed entry window."""
        earliest = time(*map(int, self.cfg.strategy.earliest_entry_time.split(":")))
        latest = time(*map(int, self.cfg.strategy.latest_entry_time.split(":")))
        return earliest <= now.time() <= latest

    def _vix_acceptable(self, vix: float) -> bool:
        return self.cfg.strategy.min_vix <= vix <= self.cfg.strategy.max_vix
